name: design_system
description: Shared design tokens, themes, and reusable widgets.
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
