name: flutter_simple_starter
description: Single App + Modular Packages + Workspace template.
publish_to: 'none'
version: 0.1.0+1
resolution: workspace

environment:
  sdk: '>=3.11.0 <4.0.0'

workspace:
  - packages/app_core
  - packages/design_system
  - packages/feature_auth
  - packages/feature_post
  - packages/shared_contracts

dependencies:
  app_core: any
  design_system: any
  feature_auth: any
  feature_post: any
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  melos: ^7.4.0

flutter:
  uses-material-design: true
