name: app_core
description: Core capabilities for env, network, storage, and observability.
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
